version: "3.3"
services:
    quiz_app:
        build:
            context: .
            dockerfile: Quiz/Dockerfile
        ports:
            - "8080:80"
        environment:
            connectionstring: "server=localhost\\SQLEXPRESS;database=Quiz;trusted_connection=true;"
        network_mode: host